spring:
  datasource:
    username: root
    password: pass
    url: jdbc:mysql://localhost:3306/helldivers

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  server:
    port: 9000