--USE helldivers

-- Flags
INSERT INTO flag (name) VALUES ("hellpod"),("backpack"),("aerial"),("explosive"),("turret"),("suuport weapon"),("orbital"),("vehicle")

-- Stratagems
INSERT INTO stratagem (name, description, code, category, type, uses, spawn_time, cooldown) VALUES ("Supply Pack", "Supply boxes containing ammunition, with a backpack that allows the user to distribute boxes to fellow Helldivers.", "down, left, down, up, up, down", "HellpodDeployment", "Supply", -1, 5, 480)
INSERT INTO stratagem (name, description, code, category, type, uses, spawn_time, cooldown) VALUES ("Ballistic Shield Backpack", "A backpack which can be wielded as a one-handed ballistic shield, protecting against small arms fire.", "down, left, down, down, up, left", "HellpodDeployment", "Supply", -1, 5, 300)
INSERT INTO stratagem (name, description, code, category, type, uses, spawn_time, cooldown) VALUES ("Shield Generator Pack", "Encloses the wearer in a spherical shield which blocks high-speed projectiles. Has a limited lifetime once deployed.", "down, upp, left, right, left, right", "HellpodDeployment", "Supply", -1, 5, 480)
INSERT INTO stratagem (name, description, code, category, type, uses, spawn_time, cooldown) VALUES ("Jump Pack", "Enables the user to jump higher than 'gravity' and 'safety' would normally allow. Must be charged before use.", "down, up, up, down, up", "HellpodDeployment", "Supply", -1, 5, 480)
INSERT INTO stratagem (name, description, code, category, type, uses, spawn_time, cooldown) VALUES ("Guard Dog", "An autonomous drone equipped with a Liberator assault rifle, providing 360° cover. Returns to backpack to rearm.", "down, up, left, up, right, down", "HellpodDeployment", "Supply", -1, 5, 480)
INSERT INTO stratagem (name, description, code, category, type, uses, spawn_time, cooldown) VALUES ("Guard Dog Rover", "An autonomous drone equipped with a laser rifle, providing 360° cover. Returns to backpack to cool down.", "down, up, left, up, right, right", "HellpodDeployment", "Supply", -1, 5, 480)
INSERT INTO stratagem (name, description, code, category, type, uses, spawn_time, cooldown) VALUES ("Resupply", "A Hellpod containing four supply packs, to replenish personal ammunition and stims in the field.", "down, down, up, right", "HellpodDeployment", "Supply", -1, 7.5, 180)

INSERT INTO stratagem (name, description, code, category, type, uses, spawn_time, cooldown) VALUES ("Eagle Strafing Run", "A strafing run of the battlefield to clear small targets, delivered almost instantly. The F-89 EAGLE is a jet fighter capable of carrying large amounts of ordnance as well as both atmospheric and limited spaceflight. The F-89 comes equipped with a 23mm cannon that can be used for strafing runs against ground targets. <br>Once the Eagle is assigned to follow you into combat you can choose additional payloads for it to carry. The EAGLE is capable of delivering its ordnance with very low time intervals, but has limited carrying capacity and needs to be sent back to be rearmed should it run out. <br>The eagle is also susceptible to enemy anti-air weaponry and caution is advised when calling in strikes near enemy AA.", "up, right, right", "CloseAirSupport", "Offensive", 3, 0, 15)
INSERT INTO stratagem (name, description, code, category, type, uses, spawn_time, cooldown) VALUES ("Eagle 500kg Bomb", "A large bomb obliterating almost any target close to impact. Make sure to clear the area. The DMB-500 is a evolution on the classic bombs of human history. The approach of not having any guidance system in the bomb has allowed for packing it with unprecedented amounts of conventional explosives, making for a very large explosion and resulting crater. While the bomb is not specifically designed to take out armored targets, the explosion is massive enough that a close hit will kill almost anything, armored or not. The drawback is that the Eagle pilot has to take more care when delivering the payload to make sure that the target is hit, this increases the response time of the bomb in comparison to other Eagle payloads.", "up, right, down, down, down", "CloseAirSupport", "Offensive", 1, 0, 15)
INSERT INTO stratagem (name, description, code, category, type, uses, spawn_time, cooldown) VALUES ("Eagle 110mm Rocket Pods", "A barrage of rocket pods, which the Eagle pilot will release on the largest target near the stratagem beacon. A pod of 110mm DRAGON rockets used to strike at armored targets. Your Eagle pilot will try to pick the best target available based on proximity to your beacon and armor level. The rockets have no guidance and will not always hit the target but this is usually compensated by firing a substantial amount of rockets. The amount of rockets means there might be significant collateral damage in proximity to the target.", "up, right, up, left", "CloseAirSupport", "Offensive", 2, 0, 15)
INSERT INTO stratagem (name, description, code, category, type, uses, spawn_time, cooldown) VALUES ("Eagle Airstrike", "A barrage of bombs creating a non-targeted carpet of explosions. A rack of semi-guided 100-kg bombs, intended to be dropped on a area target in a high speed flyby. The bomb pattern produces a carpet of explosions killing most infantry, but has a harder time affecting armored targets unless they are directly hit by one of the bombs. A great option for creating pause in an enemy advance or taking out larger concentrations of infantry.", "up, right, up, right", "CloseAirSupport", "Offensive", 2, 0, 15)
INSERT INTO stratagem (name, description, code, category, type, uses, spawn_time, cooldown) VALUES ("Eagle Napalm Airstrike", "A barrage of napalm bombs, creating a wall of fire which will stop the enemy in their tracks. The Napalm airstrike drops a row of bombs containing an extremely flammable liquid with a fairly long burn time, effectively creating a wall of fire. Great for stopping the enemy in their tracks as a universal rule for all life in the galaxy seems to be to avoid fire. The fire doesn't burn hot enough to do any significant damage to heavily armored targets.", "up, right, down, up", "CloseAirSupport", "Offensive", 2, 0, 15)

INSERT INTO stratagem (name, description, code, category, type, uses, spawn_time, cooldown) VALUES ("Shield Generator Relay", "A stationary energy shield which provides cover against projectiles. Has a limited lifetime once deployed.", "down, down, left, right, left, right", "HellpodDeployment", "Defensive", -1, 0, 90)
INSERT INTO stratagem (name, description, code, category, type, uses, spawn_time, cooldown) VALUES ("HMG Emplacement", "A manned fortification offering superior firepower against lightly armored targets. Slow to turn, so place it wisely. The E/HMG-23 HEAVY MACHINEGUN is a turret requiring a crew of 1, armed with two highly destructive 12.5mm machineguns. The emplacement is extremely good at handling large amounts of medium armored enemies. Caution should be used when manning the E/HMG-23 as crew members are exposed to enemy fire while crewing the weapon.", "down, up, left, right, right, left", "HellpodDeployment", "Defensive", -1, 3, 180)
INSERT INTO stratagem (name, description, code, category, type, uses, spawn_time, cooldown) VALUES ("Anti-Personnel Minefield", "Deploys a defensive anti-personnel minefield, to halt enemy advance.", "down, left, up, right", "HellpodDeployment", "Defensive", -1, 3, 180)
INSERT INTO stratagem (name, description, code, category, type, uses, spawn_time, cooldown) VALUES ("Incendiary Mines", "Deploys a defensive incendiary minefield, which will set both terrain and targets alight when triggered.", "down, left, left, down", "HellpodDeployment", "Defensive", -1, 3, 180)

INSERT INTO stratagem (name, description, code, category, type, uses, spawn_time, cooldown) VALUES ("Orbital Precision Strike", "A single precision shot from the Destroyer's 'ATLAS' cannon. Super Earth issued a contract for creation of a new main armament for the Super Destroyers of the HELLDIVERS. The contract was won by MORGUNSON who developed the LIBERTY CANNON able to deliver precise shots from relatively long distances delivering various kinds of ammunition.", "right, right, up", "OrbitalFireSupport", "Offensive", -1, 4, 100)

-- Links
INSERT INTO stratagem_flag_links (stratagem_id, flag_id) VALUES ( (SELECT stratagem_id FROM stratagem WHERE name = 'Supply Pack'), (SELECT flag_id FROM flag WHERE name = 'hellpod') )
INSERT INTO stratagem_flag_links (stratagem_id, flag_id) VALUES ( (SELECT stratagem_id FROM stratagem WHERE name = 'Supply Pack'), (SELECT flag_id FROM flag WHERE name = 'backpack') )
INSERT INTO stratagem_flag_links (stratagem_id, flag_id) VALUES ( (SELECT stratagem_id FROM stratagem WHERE name = 'Ballistic Shield Backpack'), (SELECT flag_id FROM flag WHERE name = 'hellpod') )
INSERT INTO stratagem_flag_links (stratagem_id, flag_id) VALUES ( (SELECT stratagem_id FROM stratagem WHERE name = 'Ballistic Shield Backpack'), (SELECT flag_id FROM flag WHERE name = 'backpack') )
INSERT INTO stratagem_flag_links (stratagem_id, flag_id) VALUES ( (SELECT stratagem_id FROM stratagem WHERE name = 'Shield Generator Pack'), (SELECT flag_id FROM flag WHERE name = 'hellpod') )
INSERT INTO stratagem_flag_links (stratagem_id, flag_id) VALUES ( (SELECT stratagem_id FROM stratagem WHERE name = 'Shield Generator Pack'), (SELECT flag_id FROM flag WHERE name = 'backpack') )
INSERT INTO stratagem_flag_links (stratagem_id, flag_id) VALUES ( (SELECT stratagem_id FROM stratagem WHERE name = 'Jump Pack'), (SELECT flag_id FROM flag WHERE name = 'hellpod') )
INSERT INTO stratagem_flag_links (stratagem_id, flag_id) VALUES ( (SELECT stratagem_id FROM stratagem WHERE name = 'Jump Pack'), (SELECT flag_id FROM flag WHERE name = 'backpack') )
INSERT INTO stratagem_flag_links (stratagem_id, flag_id) VALUES ( (SELECT stratagem_id FROM stratagem WHERE name = 'Guard Dog'), (SELECT flag_id FROM flag WHERE name = 'hellpod') )
INSERT INTO stratagem_flag_links (stratagem_id, flag_id) VALUES ( (SELECT stratagem_id FROM stratagem WHERE name = 'Guard Dog'), (SELECT flag_id FROM flag WHERE name = 'backpack') )
INSERT INTO stratagem_flag_links (stratagem_id, flag_id) VALUES ( (SELECT stratagem_id FROM stratagem WHERE name = 'Guard Dog Rover'), (SELECT flag_id FROM flag WHERE name = 'hellpod') )
INSERT INTO stratagem_flag_links (stratagem_id, flag_id) VALUES ( (SELECT stratagem_id FROM stratagem WHERE name = 'Guard Dog Rover'), (SELECT flag_id FROM flag WHERE name = 'backpack') )
INSERT INTO stratagem_flag_links (stratagem_id, flag_id) VALUES ( (SELECT stratagem_id FROM stratagem WHERE name = 'Resupply'), (SELECT flag_id FROM flag WHERE name = 'hellpod') )

INSERT INTO stratagem_flag_links (stratagem_id, flag_id) VALUES ( (SELECT stratagem_id FROM stratagem WHERE name = 'Eagle Strafing Run'), (SELECT flag_id FROM flag WHERE name = 'aerial') )
INSERT INTO stratagem_flag_links (stratagem_id, flag_id) VALUES ( (SELECT stratagem_id FROM stratagem WHERE name = 'Eagle 500kg Bomb'), (SELECT flag_id FROM flag WHERE name = 'aerial') )
INSERT INTO stratagem_flag_links (stratagem_id, flag_id) VALUES ( (SELECT stratagem_id FROM stratagem WHERE name = 'Eagle 500kg Bomb'), (SELECT flag_id FROM flag WHERE name = 'explosive') )
INSERT INTO stratagem_flag_links (stratagem_id, flag_id) VALUES ( (SELECT stratagem_id FROM stratagem WHERE name = 'Eagle 110mm Rocket Pods'), (SELECT flag_id FROM flag WHERE name = 'aerial') )
INSERT INTO stratagem_flag_links (stratagem_id, flag_id) VALUES ( (SELECT stratagem_id FROM stratagem WHERE name = 'Eagle 110mm Rocket Pods'), (SELECT flag_id FROM flag WHERE name = 'explosive') )
INSERT INTO stratagem_flag_links (stratagem_id, flag_id) VALUES ( (SELECT stratagem_id FROM stratagem WHERE name = 'Eagle Airstrike'), (SELECT flag_id FROM flag WHERE name = 'aerial') )
INSERT INTO stratagem_flag_links (stratagem_id, flag_id) VALUES ( (SELECT stratagem_id FROM stratagem WHERE name = 'Eagle Airstrike'), (SELECT flag_id FROM flag WHERE name = 'explosive') )
INSERT INTO stratagem_flag_links (stratagem_id, flag_id) VALUES ( (SELECT stratagem_id FROM stratagem WHERE name = 'Eagle Napalm Airstrike'), (SELECT flag_id FROM flag WHERE name = 'aerial') )
INSERT INTO stratagem_flag_links (stratagem_id, flag_id) VALUES ( (SELECT stratagem_id FROM stratagem WHERE name = 'Eagle Napalm Airstrike'), (SELECT flag_id FROM flag WHERE name = 'explosive') )

INSERT INTO stratagem_flag_links (stratagem_id, flag_id) VALUES ( (SELECT stratagem_id FROM stratagem WHERE name = 'Shield Generator Relay'), (SELECT flag_id FROM flag WHERE name = 'hellpod') )
INSERT INTO stratagem_flag_links (stratagem_id, flag_id) VALUES ( (SELECT stratagem_id FROM stratagem WHERE name = 'HMG Emplacement'), (SELECT flag_id FROM flag WHERE name = 'hellpod') )
INSERT INTO stratagem_flag_links (stratagem_id, flag_id) VALUES ( (SELECT stratagem_id FROM stratagem WHERE name = 'Anti-Personnel Minefield'), (SELECT flag_id FROM flag WHERE name = 'hellpod') )
INSERT INTO stratagem_flag_links (stratagem_id, flag_id) VALUES ( (SELECT stratagem_id FROM stratagem WHERE name = 'Anti-Personnel Minefield'), (SELECT flag_id FROM flag WHERE name = 'explosive') )
INSERT INTO stratagem_flag_links (stratagem_id, flag_id) VALUES ( (SELECT stratagem_id FROM stratagem WHERE name = 'Incendiary Mines'), (SELECT flag_id FROM flag WHERE name = 'hellpod') )
INSERT INTO stratagem_flag_links (stratagem_id, flag_id) VALUES ( (SELECT stratagem_id FROM stratagem WHERE name = 'Incendiary Mines'), (SELECT flag_id FROM flag WHERE name = 'explosive') )

INSERT INTO stratagem_flag_links (stratagem_id, flag_id) VALUES ( (SELECT stratagem_id FROM stratagem WHERE name = 'Orbital Precision Strike'), (SELECT flag_id FROM flag WHERE name = 'explosive') )
INSERT INTO stratagem_flag_links (stratagem_id, flag_id) VALUES ( (SELECT stratagem_id FROM stratagem WHERE name = 'Orbital Precision Strike'), (SELECT flag_id FROM flag WHERE name = 'orbital') )

-- Weapons
INSERT INTO weapon (name, description, type, damage, capacity, recoil, fire_rate, position) VALUES ("AR-23 Liberator", "The SEAF standard assualt rifle, balancing power, fire rate, and weight for a reliable weapon against smaller targets.", 1, 55, 45, 15, 640, 1)
INSERT INTO weapon (name, description, type, damage, capacity, recoil, fire_rate, position) VALUES ("AR-23P Liberator Penetrator", "A modified Liberator featuring a scope and firing armor-piercing rounds, to help users take down armored targets.", 1, 45, 30, 19, 640, 1)
INSERT INTO weapon (name, description, type, damage, capacity, recoil, fire_rate, position) VALUES ("AR-23C Liberator Concussive", "A modified Liberator featuring explosive rounds and a red-dot sight. Trades increased damage for increased recoil.", 1, 55, 30, 28, 320, 1)
INSERT INTO weapon (name, description, type, damage, capacity, recoil, fire_rate, position) VALUES ("SG-8 Punisher", "A powerful dual magazine pump-action shotgun, with limited armor penetration. Ideal for small and fast targets.", 2, 405, 16, 120, 80, 1)
INSERT INTO weapon (name, description, type, damage, capacity, recoil, fire_rate, position) VALUES ("SG-8P Punisher Plasma", "A modified Punisher shotgun firing exploding plasma rounds. Fire carefully - exploding plasma can injure squadmates.", 2, 100, 8, 110, 80, 1)
INSERT INTO weapon (name, description, type, damage, capacity, recoil, fire_rate, position) VALUES ("SG-8S Slugger", "A modified Punisher shotgun firing heavy, high-damage slug rounds. Perfect for punching holes in big targets.", 2, 250, 16, 120, 80, 1)
INSERT INTO weapon (name, description, type, damage, capacity, recoil, fire_rate, position) VALUES ("SG-225 Breaker", "A fully-automatic shotgun with a high rate of fire, excellent for controlling crowds. Requires frequent reloading.", 2, 330, 13, 55, 300, 1)
INSERT INTO weapon (name, description, type, damage, capacity, recoil, fire_rate, position) VALUES ("SG-225IE Breaker Incendiary", "A modified Breaker shotgun firing incendiary projectiles. Generates heat during use, so limited to burst fire.", 2, 240, 25, 28, 300, 1)
INSERT INTO weapon (name, description, type, damage, capacity, recoil, fire_rate, position) VALUES ("SG-225SP Breaker Spray & Pray", "A modified Breaker shotgun firing birdshot, small pellets which saturate an area to clear up smaller targets.", 2, 192, 26, 45, 330, 1)
INSERT INTO weapon (name, description, type, damage, capacity, recoil, fire_rate, position) VALUES ("ARC-12 Blitzer", "This shotgun blasts a wide burst of high-voltage electricity that arcs between all units - enemy or otherwise - within range.", 2, 250, 999, 60, 30, 1)
INSERT INTO weapon (name, description, type, damage, capacity, recoil, fire_rate, position) VALUES ("SMG-37 Defender", "A high-caliber submachine gun which can be fired with one hand. Has a relatively low rate of fire.", 3, 70, 45, 10, 520, 1)
INSERT INTO weapon (name, description, type, damage, capacity, recoil, fire_rate, position) VALUES ("R-63 Diligence", "This high-caliber marksman rifle trades magazine capacity and rate of fire for powerful, accurate shots.", 4, 112, 20, 35, 350, 1)
INSERT INTO weapon (name, description, type, damage, capacity, recoil, fire_rate, position) VALUES ("R-63CS Diligence Counter Sniper", "A modified Diligence rifle offering increased damage, but a reduced rate of fire. Fires a single bullet at a time.", 4, 128, 15, 53, 350, 1)
INSERT INTO weapon (name, description, type, damage, capacity, recoil, fire_rate, position) VALUES ("LAS-5 Scythe", "A laser rifle firing a continuous beam. Does not need reloading, but if it overheats a new heat sink must be fitted.", 5, 300, 8, 1, 0, 1)
INSERT INTO weapon (name, description, type, damage, capacity, recoil, fire_rate, position) VALUES ("LAS-16 Sickle", "A laser rifle, firing in short bursts. Does not need reloading, but if it overheats a new heat sink must be fitted.", 5, 55, 9, 2, 750, 1)
INSERT INTO weapon (name, description, type, damage, capacity, recoil, fire_rate, position) VALUES ("PLAS-1 Scorcher", "A plasma rifle, firing a bolt of superheated gas which explodes on impact. Avoid standing in proximity to the blast.", 5, 100, 15, 20, 250, 1)
INSERT INTO weapon (name, description, type, damage, capacity, recoil, fire_rate, position) VALUES ("JAR-5 Dominator", "Firing jet-propelled rounds, the Dominator trades fire rate and magazine capacity for increased damage per projectile.", 6, 300, 15, 75, 250, 1)


-- Weapon Modes
INSERT INTO weapon_modes (weapon_id, mode) VALUES (1,"SEMI_AUTOMATIC"), (1,"BURST"), (1,"AUTOMATIC")
INSERT INTO weapon_modes (weapon_id, mode) VALUES (2,"SEMI_AUTOMATIC"), (2,"BURST"), (2,"AUTOMATIC")
INSERT INTO weapon_modes (weapon_id, mode) VALUES (3,"SEMI_AUTOMATIC"), (3,"AUTOMATIC")
INSERT INTO weapon_modes (weapon_id, mode) VALUES (4,"PUMP_ACTION")
INSERT INTO weapon_modes (weapon_id, mode) VALUES (5,"PUMP_ACTION")
INSERT INTO weapon_modes (weapon_id, mode) VALUES (6,"PUMP_ACTION")
INSERT INTO weapon_modes (weapon_id, mode) VALUES (7,"SEMI_AUTOMATIC"), (7,"AUTOMATIC")
INSERT INTO weapon_modes (weapon_id, mode) VALUES (8,"SEMI_AUTOMATIC"), (8,"AUTOMATIC")
INSERT INTO weapon_modes (weapon_id, mode) VALUES (9,"SEMI_AUTOMATIC"), (9,"AUTOMATIC")
INSERT INTO weapon_modes (weapon_id, mode) VALUES (10,"SEMI_AUTOMATIC")
INSERT INTO weapon_modes (weapon_id, mode) VALUES (11,"SEMI_AUTOMATIC"), (11,"AUTOMATIC")
INSERT INTO weapon_modes (weapon_id, mode) VALUES (12,"SEMI_AUTOMATIC")
INSERT INTO weapon_modes (weapon_id, mode) VALUES (13,"SEMI_AUTOMATIC")
INSERT INTO weapon_modes (weapon_id, mode) VALUES (14,"AUTOMATIC")
INSERT INTO weapon_modes (weapon_id, mode) VALUES (15,"AUTOMATIC")
INSERT INTO weapon_modes (weapon_id, mode) VALUES (16,"SEMI_AUTOMATIC")
INSERT INTO weapon_modes (weapon_id, mode) VALUES (17,"SEMI_AUTOMATIC")

-- Weapon Traits
INSERT INTO weapon_traits (weapon_id, trait) VALUES (1,"LIGHT_ARMOR_PENETRATING")
INSERT INTO weapon_traits (weapon_id, trait) VALUES (2,"LIGHT_ARMOR_PENETRATING"), (2, "MEDIUM_ARMOR_PENETRATING")
INSERT INTO weapon_traits (weapon_id, trait) VALUES (3,"LIGHT_ARMOR_PENETRATING"), (3, "EXPLOSIVE")
INSERT INTO weapon_traits (weapon_id, trait) VALUES (4,"LIGHT_ARMOR_PENETRATING"), (4, "ROUNDS_RELOAD")
INSERT INTO weapon_traits (weapon_id, trait) VALUES (5,"EXPLOSIVE")
INSERT INTO weapon_traits (weapon_id, trait) VALUES (6,"MEDIUM_ARMOR_PENETRATING"), (6, "ROUNDS_RELOAD")
INSERT INTO weapon_traits (weapon_id, trait) VALUES (7,"LIGHT_ARMOR_PENETRATING")
INSERT INTO weapon_traits (weapon_id, trait) VALUES (8,"LIGHT_ARMOR_PENETRATING"), (8, "INCENDIARY")
INSERT INTO weapon_traits (weapon_id, trait) VALUES (9,"LIGHT_ARMOR_PENETRATING")
INSERT INTO weapon_traits (weapon_id, trait) VALUES (10,"NONE")
INSERT INTO weapon_traits (weapon_id, trait) VALUES (11,"LIGHT_ARMOR_PENETRATING"), (11, "ONE_HANDED")
INSERT INTO weapon_traits (weapon_id, trait) VALUES (12,"LIGHT_ARMOR_PENETRATING")
INSERT INTO weapon_traits (weapon_id, trait) VALUES (13,"MEDIUM_ARMOR_PENETRATING")
INSERT INTO weapon_traits (weapon_id, trait) VALUES (14,"LIGHT_ARMOR_PENETRATING"), (14, "BEAM"), (14, "HEAT")
INSERT INTO weapon_traits (weapon_id, trait) VALUES (15,"LIGHT_ARMOR_PENETRATING"), (15, "HEAT")
INSERT INTO weapon_traits (weapon_id, trait) VALUES (16,"LIGHT_ARMOR_PENETRATING"), (16, "EXPLOSIVE")
INSERT INTO weapon_traits (weapon_id, trait) VALUES (17,"MEDIUM_ARMOR_PENETRATING")

-- Enemy
INSERT INTO enemy (name, description, type) VALUES ("Scavenger", "The lowliest of the Terminids, the Scavenger embodies mindless aggression and blind obedience to the hive's insatiable appetite for destruction.", "TERMINID")
INSERT INTO enemy (name, description, type) VALUES ("Warrior", "Warriors embody a relentless pursuit of mindless expansion and destruction.", "TERMINID")
INSERT INTO enemy (name, description, type) VALUES ("Hunter", "The elusive Hunters epitomize the relentless pursuit of prey within the Terminid swarm.", "TERMINID")
INSERT INTO enemy (name, description, type) VALUES ("Stalker", "Stalkers epitomize stealth and subterfuge within the Terminid ranks, lurking in the shadows and striking with lethal precision.", "TERMINID")
INSERT INTO enemy (name, description, type) VALUES ("Bile Spewer", "The grotesque Bile Spewer is a product of catastrophic chemical spills on Terminid E-710 farms, its bloated thorax brimming with corrosive acids ready to unleash upon encountering the forces of Democracy.", "TERMINID")
INSERT INTO enemy (name, description, type) VALUES ("Charger", "The Charger presents a formidable threat on the battlefield, boasting a meter-thick exoskeleton that renders it nearly impervious to conventional weaponry.", "TERMINID")
INSERT INTO enemy (name, description, type) VALUES ("Brood Commander", "Behold, the Brood Commander - a towering monstrosity of armored menace, leading the Terminid horde with a ruthless determination to crush democracy beneath its spiky claws. ", "TERMINID")
INSERT INTO enemy (name, description, type) VALUES ("Bile Titan", "Prepare yourselves, Helldivers, for the ultimate test of courage and firepower - the monstrous Bile Titan.", "TERMINID")
INSERT INTO enemy (name, description, type) VALUES ("Shrieker", "Just as our research had foretold, we've detected flying bugs.", "TERMINID")
INSERT INTO enemy (name, description, type) VALUES ("Trooper", "Troopers epitomize the heartless fusion of man and machine, a grotesque testament to the Automaton faction's relentless pursuit of destruction. ", "AUTOMATON")
INSERT INTO enemy (name, description, type) VALUES ("Commissar", "The Commissar embodies a crude imitation of military leadership, its mechanical form augmented with slightly faster processing and a rudimentary command subroutine. ", "AUTOMATON")
INSERT INTO enemy (name, description, type) VALUES ("Scout Strider", "A walking fortress operated by a lesser machine, guided by the crude intelligence of an Automaton Trooper. ", "AUTOMATON")
INSERT INTO enemy (name, description, type) VALUES ("Berserker", "A primitive actualization of barbarity, the Berserker epitomizes the Automaton faction's relentless pursuit of brutality.", "AUTOMATON")
INSERT INTO enemy (name, description, type) VALUES ("Devastator", "The ironclad Devastator embodies the relentless might of the Automaton faction, a formidable adversary armed with a diverse array of heinous weaponry. ", "AUTOMATON")
INSERT INTO enemy (name, description, type) VALUES ("Hulk", "As with all Automaton units, the plodding Hulk epitomizes brute force and relentless aggression, its towering form bristling with heavy weaponry designed for maximum destruction. ", "AUTOMATON")
INSERT INTO enemy (name, description, type) VALUES ("Tank", "Modeled after Super Earth tank designs, the Automaton Annihilator Tank stands as a crude imitation of its Super Earth counterpart, albeit plainly inferior in numerous aspects. ", "AUTOMATON")
INSERT INTO enemy (name, description, type) VALUES ("Factory Strider", "Stand by for further details...", "AUTOMATON")
INSERT INTO enemy (name, description, type) VALUES ("Gunship", "Automatons have finally made a breakthrough: the dropships are UAVs armed to the teeth with rockets, cannons, and other artillery.", "AUTOMATON")
INSERT INTO enemy (name, description, type) VALUES ("Dropship", "Packed to the brim with robotic infantry, Dropships serve as the vanguard of the Automatons' relentless assault.", "AUTOMATON")

-- Player
INSERT INTO player (name, email, gamer_tag, type) VALUES ("Rocket Raccoon", "rraccoon1990@gmail.com", "the1andOnly", "BEAST")