spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/v1/employees/**
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/api/v1/departments/**
  config:
    import: "optional:configserver:http://localhost:8028"

server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

# For ZipKin
management:
  tracing:
    sampling:
      probability: 1.0