version: '3.8'

services:
  strapi:
    image: naskio/strapi
    container_name: strapi_cms2
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "1338:1337"
    volumes:
      - strapi_app:/srv/app
    environment:
      NODE_ENV: development
      DATABASE_CLIENT: mysql
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - mysqldb_default

volumes:
  strapi_app:

networks:
  mysqldb_default:
    external: true
