services:
    wordpress:
        image: wordpress:latest
        volumes:
          - wp_data:/var/www/html
        ports:
          - 9090:80
        restart: always
        env_file: .env
        environment:
          - WORDPRESS_DB_HOST=mysql:${MYSQL_PORT}
          - WORDPRESS_DB_USER=${MYSQL_USER}
          - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
          - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
        networks:
          - mysqldb_default
volumes:
  wp_data:
networks:
  mysqldb_default:
    external: true