version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile  # Make sure this points to the correct Dockerfile
    ports:
      - "9091:8000"
    depends_on:
      - redis
    environment:
      - DATABASE_URL=mysql+pymysql://root:pass@localhost/clinical_trials
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app

  redis:
    image: redis:latest
    container_name: clinical_trials_redis
    restart: always
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    container_name: clinical_trials_celery
    restart: always
    depends_on:
      - redis
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      DATABASE_URL: mysql+pymysql://root:pass@localhost/clinical_trials
    command: celery -A backend.tasks.celery_app worker --loglevel=info

  celery_beat:
    build: .
    container_name: clinical_trials_celery_beat
    restart: always
    depends_on:
      - redis
      - celery_worker
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
    command: celery -A backend.tasks.celery_app beat --loglevel=info

  flower:
    image: mher/flower
    container_name: clinical_trials_flower
    restart: always
    depends_on:
      - redis
      - celery_worker
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
    ports:
      - "5555:5555"