package com.helldivers.enums.matches;

public enum Type {
    EMERGENCY_EVACUATION,
    LAUNCH_ICBM,
    BLITZ_SEARCH_AND_DESTROY,
    PURGE_HATCHERIES,
    RETRIEVE_VALUABLE_DATA,
    CONDUCT_GEOLOGICAL_SURVEY,
    ERADICATE_TERMINID_SWARM,
    ELIMINATE_BILE_TITANS
}
